import { Role } from "@prisma/client";

export const users = [
  {
    id: 'user1-uuid',
    email: 'user1@example.com',
    nickName: 'user1',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie1.jpg',
    role: Role.admin,
    createdAt: new Date(),
    teamId: 'team1-uuid',
  },
  {
    id: 'user2-uuid',
    email: 'user2@example.com',
    nickName: 'user2',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie2.jpg',
    role: Role.organizer,
    createdAt: new Date(),
    teamId: 'team1-uuid',
  },
  {
    id: 'user3-uuid',
    email: 'user3@example.com',
    nickName: 'user3',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie3.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team1-uuid',
  },
  {
    id: 'user4-uuid',
    email: 'user4@example.com',
    nickName: 'user4',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie4.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team1-uuid',
  },
  {
    id: 'user5-uuid',
    email: 'user5@example.com',
    nickName: 'user5',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie5.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team1-uuid',
  },
  {
    id: 'user6-uuid',
    email: 'user6@example.com',
    nickName: 'user6',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie6.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team2-uuid',
  },
  {
    id: 'user7-uuid',
    email: 'user7@example.com',
    nickName: 'user7',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie7.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team2-uuid',
  },
  {
    id: 'user8-uuid',
    email: 'user8@example.com',
    nickName: 'user8',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie8.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team2-uuid',
  },
  {
    id: 'user9-uuid',
    email: 'user9@example.com',
    nickName: 'user9',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie9.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team2-uuid',
  },
  {
    id: 'user10-uuid',
    email: 'user10@example.com',
    nickName: 'user10',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie10.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team2-uuid',
  },
  {
    id: 'user11-uuid',
    email: 'user11@example.com',
    nickName: 'user11',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie11.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team3-uuid',
  },
  {
    id: 'user12-uuid',
    email: 'user12@example.com',
    nickName: 'user12',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie12.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team3-uuid',
  },
  {
    id: 'user13-uuid',
    email: 'user13@example.com',
    nickName: 'user13',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie13.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team3-uuid',
  },
  {
    id: 'user14-uuid',
    email: 'user14@example.com',
    nickName: 'user14',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie14.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team3-uuid',
  },
  {
    id: 'user15-uuid',
    email: 'user15@example.com',
    nickName: 'user15',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie15.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team3-uuid',
  },
  {
    id: 'user16-uuid',
    email: 'user16@example.com',
    nickName: 'user16',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie16.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team4-uuid',
  },
  {
    id: 'user17-uuid',
    email: 'user17@example.com',
    nickName: 'user17',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie17.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team4-uuid',
  },
  {
    id: 'user18-uuid',
    email: 'user18@example.com',
    nickName: 'user18',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie18.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team4-uuid',
  },
  {
    id: 'user19-uuid',
    email: 'user19@example.com',
    nickName: 'user19',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie19.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team4-uuid',
  },
  {
    id: 'user20-uuid',
    email: 'user20@example.com',
    nickName: 'user20',
    password: 'password123',
    birthDate: '2000-02-01T00:00:00.000Z',
    urlSelfie: 'https://example.com/selfie20.jpg',
    role: Role.user,
    createdAt: new Date(),
    teamId: 'team4-uuid',
  },
];