import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/provider";
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Stream Games Tournaments",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.png" />
        <title>Stream Games Tournaments</title>
      </Head>
      <Providers>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
          <NavBar />
            <main className="flex-grow">
              {children}
              <Toaster position="bottom-right"/>
            </main>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
